demo/config/routes.rb
Demo::Application.routes.draw do

  get "log_in" => "sessions#new", :as => "log_in"

  get "log_out" => "sessions#destroy", :as => "log_out"

  get "sign_up" => "users#new", :as => "sign_up"

  get "say/hello"

  get "say/goodbye"

  get "articles/:id/show" => "articles#show"

  root :to => "users#new" 

  resources :categories, :products, :users, :sessions

  resources :articles do
    resources :comments
  end

  namespace :admin do
    resources :articles
  end

end

demo/app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :price, :description, :user_id
  belongs_to :user
  has_many :categories, :through => :categories_products
  has_many :categories_products

  scope :price_greater_than_thousand, where("price>1000")
  scope :red, where("name like '%red%'")

  validates :name,  :presence => true,
    :uniqueness => true
  
  validates :price,  :numericality => true

  validates :description,  :presence => true
end

demo/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def new
    @product = Product.new
    @users = User.all
  end

  def create
    @product = Product.new(params[:product])
    if @product.save
      flash[:notice] = "Data was successfully saved"
      redirect_to products_path
    else
      render new_product_path
    end
  end

  def edit
    @product = Product.find(params[:id])
    @users = User.all
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(params[:product])
      flash[:notice] = "Data was successfully saved"
      redirect_to products_path
    else
      render new_product_path
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "Data was successfully deleted"
    redirect_to products_path
  end

  def index
    @products = Product.all
  end
end

demo/app/helpers/products_helper.rb
module ProductsHelper
end

demo/app/views/products/edit.html.erb
<%= form_for @product do |f| %>
  <% if @product.errors.any? %>
    <%= pluralize(@product.errors.count, "error") %> :
    <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  User: <%= collection_select(:product, :user_id, @users, :id, :username, {:prompt => false}) %><br/>
  Name: <%= f.text_field :name %><br/>
  Description: <%= f.text_area :description %><br/>
  Price: <%= f.text_field :price, :size => 10 %><br/>
  <%=f.submit :Submit%>
<% end %>
<%= link_to "Back", products_path %>

demo/app/views/products/index.html.erb
<%= flash[:notice] %><br/>
<%= link_to "Add New", new_product_path %>
<table border="1">
  <tr>
    <td>Name</td>
    <td>Description</td>
    <td>Price</td>
    <td>User</td>
    <td>Action</td>
  </tr>
  <% @products.each do |product| %>
    <tr>
      <td><%= product.name %></td>
      <td><%= product.description %></td>
      <td><%= product.price %></td>
      <td><%= product.user.username %></td>
      <td>
        <%= link_to "Edit", edit_product_path(product.id) %>
        <%= link_to "Delete", product_path(product.id), :method=>:delete, :confirm => "Are you sure?" %>
      </td>
    </tr>
  <% end %>
</table>

demo/app/views/products/new.html.erb
<%= form_for @product do |f| %>
  <% if @product.errors.any? %>
    <%= pluralize(@product.errors.count, "error") %> :
    <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  User: <%= collection_select(:product, :user_id, @users, :id, :username, {:prompt => false}) %><br/>
  Name: <%= f.text_field :name %><br/>
  Description: <%= f.text_area :description %><br/>
  Price: <%= f.text_field :price, :size => 10 %><br/>
  <%=f.submit :Submit%>
<% end %>
<%= link_to "Back", products_path %>