final_project/config/routes.rb
FinalProject::Application.routes.draw do
  
  get "log_in" => "sessions#new", :as => "log_in"

  get "log_out" => "sessions#destroy", :as => "log_out"

  get "sign_up" => "users#new", :as => "sign_up"
  
  root :to => "products#dashboard"

  resources :products, :users, :sessions
  
  resources :articles do
    resources :comments
  end

  namespace :admin do
    resources :categories
  end
end

final_project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Final Project</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application", :media => "all" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="container">
      <header>
        <h1 align="center">WELCOME TO MY STORE</h1>
      </header>
      <nav>
        <ul>
          <%= raw(menu_sign_up) %>
          <li>
            <%= link_to "Products", products_path %>
          </li>
          <li>
            <%= link_to "Article", articles_path %>
          </li>
          <% if !current_user.nil? && current_user.is_admin %>
            <li>
              <%= link_to "Category", admin_categories_path %>
            </li>
          <% end %>

        </ul>
        <div class="clear"></div>
      </nav>
      <%= flash[:error] %><br/>
      <%= flash[:notice] %><br/>
      <div id="content">
        <aside>
          <% if !current_user %>
            <div class="cls-login">
              <%= render :partial => 'sessions/new' %>
            </div>
          <% else %>
            <div class="profil">
              <%= render :partial => 'users/profil' %>
            </div>
            <div class="list-category">
              <%= render :partial => 'admin/categories/list' %>
            </div>
          <%end%>
        </aside>
        <div id="right-side">
          <%= yield %>
        </div>
        <div class="clear"></div>
      </div>
    </div>
  </body>
</html>