final_project/config/routes.rb
FinalProject::Application.routes.draw do
  
  get "log_in" => "sessions#new", :as => "log_in"

  get "log_out" => "sessions#destroy", :as => "log_out"

  get "sign_up" => "users#new", :as => "sign_up"
  
  root :to => "products#dashboard"

  resources :products, :users, :sessions
  
  resources :articles do
    resources :comments
  end

  namespace :admin do
    resources :categories
  end
end

final_project/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :password, :password_confirmation, :email, :gender,
    :name, :address, :phone_number, :birthday, :facebook, :blog
  attr_accessor :password

  before_save :encrypt_password

  has_many :products, :dependent => :destroy
  
  has_many :articles, :dependent => :destroy

  validates :name,  :presence => true,
    :length => {:minimum => 1, :maximum => 20},
    :format => { :with => /\A[a-zA-Z]+\z/},
    :allow_nil => false,
    :uniqueness => true
  validates :email, :presence => true,
    :uniqueness => true,
    :allow_nil => false,
    :format => {:with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i}
  validates :password, :presence => {:on => :create},
    :confirmation => true
  
  def is_admin
    return self.email == "admin@admin.com"
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

final_project/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_login, :only => [:destroy, :edit, :update, :show]
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if verify_recaptcha
      if @user.save
        UserMailer.registration_confirmation(@user).deliver
        redirect_to root_path, :notice => "Signed up!"
      else
        render "new"
      end
    else
      flash[:error] = "There was an error with the recaptcha code below.
                     Please re-enter the code."
      render "new"
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:notice] = "Data was successfully saved"
      redirect_to user_path(params[:id])
    else
      render "edit"
    end
  end

  def edit
    @user = User.find(params[:id])
    @user.birthday = @user.birthday.strftime("%d-%m-%Y")
  end
end

final_project/app/helpers/users_helper.rb
module UsersHelper
end

final_project/app/views/users/_profil.html.erb
<ul class="profil-link">
  <li>
    <%= link_to "Edit Profil", edit_user_path(current_user.id) %>
  </li>
  <li>
    <%= link_to "Sell a Product", new_product_path %>
  </li>
  <li>
    <%= link_to "Share an Article", new_article_path %>
  </li>
  <li>
    <%= link_to "Logout", log_out_path , :confirm => "Are you sure?" %>
  </li>
</ul>

final_project/app/views/users/edit.html.erb
<h2>Edit Profile</h2>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h3>Form is invalid</h3>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <table>
    <tr>
      <td width="100"><%= f.label :name %></td>
      <td><%= f.text_field :name%></td>
    </tr>
    <tr>
      <td><%= f.label :email %></td>
      <td><%= f.text_field :email%></td>
    </tr>
    <tr>
      <td><%= f.label :address %></td>
      <td><%= f.text_area :address, :rows => 5 %></td>
    </tr>
    <tr>
      <td><%= f.label :phone_number %></td>
      <td><%= f.text_field :phone_number%></td>
    </tr>
    <tr>
      <td><%= f.label :birthday %></td>
      <td><%= f.text_field :birthday, :size => 10, :readonly => true  %></td>
    </tr>
    <tr>
      <td><%= f.label @user.gender %></td>
      <td>
        <%= f.radio_button :gender, true %> <%= f.label "Male" %>
        <%= f.radio_button :gender, false %> <%= f.label "Female" %>
      </td>
    </tr>
    <tr>
      <td><%= f.label :facebook %></td>
      <td><%= f.text_field :facebook%></td>
    </tr>
    <tr>
      <td><%= f.label :blog %></td>
      <td><%= f.text_field :blog%></td>
    </tr>
  </table>
  <p class="button"><%= f.submit :"Submit" %></p>
<% end %>

final_project/app/views/users/new.html.erb
<h2>Sign Up</h2>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h3>Form is invalid</h3>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <table>
    <tr>
      <td width="100"><%= f.label :name %></td>
      <td><%= f.text_field :name%></td>
    </tr>
    <tr>
      <td><%= f.label :email %></td>
      <td><%= f.text_field :email%></td>
    </tr>
    <tr>
      <td><%= f.label :password %></td>
      <td><%= f.password_field :password%></td>
    </tr>
    <tr>
      <td><%= f.label :password_confirmation %></td>
      <td><%= f.password_field :password_confirmation%></td>
    </tr>
    <tr>
      <td><%= f.label :address %></td>
      <td><%= f.text_area :address, :rows => 5 %></td>
    </tr>
    <tr>
      <td><%= f.label :phone_number %></td>
      <td><%= f.text_field :phone_number%></td>
    </tr>
    <tr>
      <td><%= f.label :birthday %></td>
      <td><%= f.text_field :birthday, :size => 10, :readonly => true  %></td>
    </tr>
    <tr>
      <td><%= f.label :gender %></td>
      <td>
        <%= f.radio_button :gender, true, option = {:checked => true} %> <%= f.label "Male" %>
        <%= f.radio_button :gender, false %> <%= f.label "Female" %>
      </td>
    </tr>
    <tr>
      <td><%= f.label :facebook %></td>
      <td><%= f.text_field :facebook%></td>
    </tr>
    <tr>
      <td><%= f.label :blog %></td>
      <td><%= f.text_field :blog%></td>
    </tr>
  </table>

  <%= recaptcha_tags %>
  <p class="button"><%= f.submit :"Submit" %></p>
<% end %>

final_project/app/views/users/show.html.erb
<h2>User Profile</h2>

<table>
  <tr>
    <td class="cls-label" width="100"><%= label_tag :name %></td>
    <td><%= current_user.name%></td>
  </tr>
  <tr>
    <td class="cls-label"><%= label_tag :email %></td>
    <td><%= current_user.email%></td>
  </tr>
  <tr>
    <td class="cls-label"><%= label_tag :address %></td>
    <td><%= current_user.address%></td>
  </tr>
  <tr>
    <td class="cls-label"><%= label_tag :phone_number %></td>
    <td><%= current_user.phone_number%></td>
  </tr>
  <tr>
    <td class="cls-label"><%= label_tag :birthday %></td>
    <td><%= current_user.birthday.strftime("%d-%m-%Y") %></td>
  </tr>
  <tr>
    <td class="cls-label"><%= label_tag :gender %></td>
    <td><%= (current_user.gender == true ?"Male":"Female") %></td>
  </tr>
  <tr>
    <td class="cls-label"><%= label_tag :facebook %></td>
    <td><%= current_user.facebook%></td>
  </tr>
  <tr>
    <td class="cls-label"><%= label_tag :blog %></td>
    <td><%= current_user.blog%></td>
  </tr>
</table>