demo/config/routes.rb
Demo::Application.routes.draw do

  get "log_in" => "sessions#new", :as => "log_in"

  get "log_out" => "sessions#destroy", :as => "log_out"

  get "sign_up" => "users#new", :as => "sign_up"

  get "say/hello"

  get "say/goodbye"

  get "articles/:id/show" => "articles#show"

  root :to => "users#new" 

  resources :categories, :products, :users, :sessions

  resources :articles do
    resources :comments
  end

  namespace :admin do
    resources :articles
  end

end

demo/app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :title, :body, :rating, :user_id
  belongs_to :user
  has_many :comments, :dependent => :destroy

  scope :certain_rating, lambda {|rate| where("rating = ?", rate) }

  validates :title,  :presence => true,
    :uniqueness => true,
    :allow_blank => false,
    :exclusion => { :in => %w(nil empty blank)}

  validates :rating,  :numericality => true

  validates :body,  :presence => true

  def self.more_than_ten_char
    where("length(body)>10")
  end
end

demo/app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::ApplicationController
  before_filter :require_admin_login
  layout 'admin'
  before_filter :check_user, :only => [:destroy]

  def check_user
    @article = Article.find(params[:id])
    if @article.user_id != session[:user_id]
      flash[:notice] = "You are not permitted delete that article "
      @articles = Article.all
      render "index"
    end
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(params[:article])
    if @article.save
      flash[:notice] = "Data was successfully saved"
      redirect_to admin_articles_path
    else
      render new_admin_article_path
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update_attributes(params[:article])
      flash[:notice] = "Data was successfully saved"
      redirect_to admin_articles_path
    else
      render new_admin_article_path
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    flash[:notice] = "Data was successfully deleted"
    redirect_to admin_articles_path
  end

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
    @comments = @article.comments
  end
end

demo/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  #  before_filter :require_login, :only => [:new, :create, :edit, :update, :destroy, :index]
  before_filter :require_login
  before_filter :require_admin_login, :only => [:new, :create, :edit, :update, :destroy]
  before_filter :check_user, :only => [:destroy]
  rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found

  def check_user
    @article = Article.find(params[:id])
    if @article.user_id != session[:user_id]
      flash[:notice] = "You are not permitted delete that article "
      @articles = Article.all
      render "index"
    end
  end
  
  def new
    @article = Article.new
  end

  def create
    @article = Article.new(params[:article])
    if @article.save
      flash[:notice] = "Data was successfully saved"
      redirect_to articles_path
    else
      flash[:error] = "Article was failed to create."
      render new_article_path
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update_attributes(params[:article])
      flash[:notice] = "Article was successfully updated."
      redirect_to articles_path
    else
      flash[:error] = "Article was failed to update."
      render new_article_path
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    flash[:notice] = "Data was successfully deleted"
    redirect_to articles_path
  end

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
    if @article.nil?
      flash[:notice] = 'Cannot find the article'
      redirect_to articles_path
    else
      @comments = @article.comments
    end
    
  end

  private
  def record_not_found
    flash[:notice] = 'Cannot find the article'
    redirect_to articles_path
  end

end

demo/app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

demo/app/helpers/articles_helper.rb
module ArticlesHelper
end

demo/app/views/articles/_comments.html.erb
<ul>
  <% @comments.each do |comment| %>
    <li><%= comment.content %></li>
  <% end %>
</ul>

demo/app/views/articles/edit.html.erb
<%= form_for @article do |f| %>
  <% if @article.errors.any? %>
    <%= pluralize(@article.errors.count, "error") %> :
    <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  Title: <%= f.text_field :title %><br/>
  Body: <%= f.text_area :body %><br/>
  Rating: <%= f.text_field :rating, :size => 10 %><br/>
  <%= f.hidden_field :user_id, :value => @current_user.id %>
  <%=f.submit :Submit%>
<% end %>
<%= link_to "Back", articles_path %>

demo/app/views/articles/index.html.erb
<%= flash[:notice] %><br/>
<%#= link_to "Add New", new_article_path %>
<table border="1">
  <tr>
    <td>Title</td>
    <td>Body</td>
    <td>Rating</td>
    <td>User</td>
    <td>Action</td>
  </tr>
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.body %></td>
      <td><%= article.rating %></td>
      <td><%= article.user.username %></td>
      <td>
        <%= link_to 'Show', :action => :show, :id => article.id %>
        <%#= link_to "Edit", edit_article_path(article.id) %>
        <%= link_to "Delete", article_path(article.id), :method=>:delete, :confirm => "Are you sure?" %>
      </td>
    </tr>
  <% end %>
</table>

demo/app/views/articles/new.html.erb
<%= form_for @article do |f| %>
  <% if @article.errors.any? %>
    <%= pluralize(@article.errors.count, "error") %> :
    <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  Title: <%= f.text_field :title %><br/>
  Body: <%= f.text_area :body %><br/>
  Rating: <%= f.text_field :rating, :size => 10 %><br/>
  <%= f.hidden_field :user_id, :value => @current_user.id %>
  <%=f.submit :Submit%>
<% end %>
<%= link_to "Back", articles_path %>

demo/app/views/articles/show.html.erb
<% if !@article.nil? %>
  <h2>Article</h2>
  User: <%= @article.user.username %><br/>
  Title: <%= @article.title %><br/>
  Body: <%= @article.body %><br/>
  Rating: <%= @article.rating %><br/><br/><br/>

  <span id="comments_count"><%= pluralize(@comments.count, "Comment") %></span>
  <div id="comments">
    <%= render :partial => "comments", :locals => {:comments => @comments}  %>
  </div><br />

  <h3>Add Comment</h3>
  <div id="comment-notice"><%= flash[:notice] %><br/></div>

  <% unless(current_user.nil?)%>
    <%= form_for([@article, @article.comments.build], :remote => true) do |f| %>
      <%= f.text_area :content %>
      <%= f.hidden_field :article_id, :value => @article.id %>
      <%= submit_tag "comment" %>
    <% end -%>
  <% end %>
<% end %>
<%= link_to "Back", articles_path %>